postgres: &defaults
  adapter: postgresql
  pool: 10
  timeout: 60000
  host: localhost
  template: template0

development:
  <<: *defaults
  database: upcoming_development

test:
  <<: *defaults
  database: upcoming_test

production:
  <<: *defaults
  database: upcoming_production
